import './globals.css'
import { Poppins } from 'next/font/google'


const poppins = Poppins({ 
  subsets: ['latin'], 
  weight: ['400', '600', '700'] })

export const metadata = {
  title: 'nextjs project',
  description: 'Generated by 3nho',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="">
          {children}
        </div>
      </body>
    </html>
  )
}
